version: "3.8"
services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    command: ["mongod", "--bind_ip_all"]  # Allow external connections
    restart: always

  go-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-app
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017  # Use the default MongoDB URI
    restart: always
